### ISSUE TITLE
Please add option to load all data as character

### ISSUE THREAD

**Issue by nielsoledam** [ogroendal/DSTget#5]
Thanks the great introduction to this package at the tuesday R-meetup at Statistics Denmark – your package seems well made and easy to use!
:-)

However, when using it I've run into a serious issue that I think needs you to add an option for loading all data as character – instead of the current solution where your package as far as I can see trys to guess the right class of each variable.

Most of the time the guessing works well, but when dealing with factor id's it makes a mess.

For example consider the table "FU51":

- The factor table ($values$FORBRUGSART) has the following entries:
```
   id:                                                                text:
   ...                                                                  ...
   314                                                     314 Opførelsesår
  1000                                                        FORBRUG I ALT
 01000                         01 FØDEVARER OG IKKE-ALKOHOLISKE DRIKKEVARER
 01111                                                         01.1.1.1 Ris
   ...                                                                  ...
```
- ...but because the actual data for the column "forbrugsart" is being loaded as integer, both " 1000" and "01000" is being converted to the integer 1000.
- ...which makes it impossible to match the labels correctly to the tabel.

Could you please consider adding an option for loading all variables as character instead – that would solve the issue without breaking existing code?

Something along the line of "dataAsCharacter = TRUE" would do the job.
;-)

**Extra info:**

1.
I load the data with the following options:
```R
metadata <- DSTget("FU51")
data <- getData(metadata,
                        labelFactors = FALSE,
                        fillRemaining = FALSE,
                        startDate = NA,
                        endDate = NA,
                        splitLarge = 100000)
```
2.
I've found some typos in the "FU51" data:
"2 Antal personer i husstanden" ---> should probably be: "256 Antal personer i husstanden"
"252 Antal børn i husstandne" ---> should be: "252 Antal børn i husstanden"

**Comment by ogroendal** [comment]
Thanks for the bug report. It should be an easy fix. I will look at something soon and add some tests to the tests suite for cases like this.

**Comment by nielsoledam** [comment]
Great to hear! :-)

Returning all data as character should also handle the issue of missing values being stated as ".." in the numeric data.

**Comment by nielsoledam** [comment]
Yes, it works nicely now – thanks for the fix.
:-)

**Comment by ogroendal** [comment]
No problem. Don't hesitate to add other issues that you might find.
